### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [miljinx/firehose-splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by jimxlin** [comment]
Hi Michael,
I added the meta tag and pushed to Github. However, I am still seeing issues when I "test" mobile behavior by resizing the browser window. When I make the window short enough, the footer overlaps the contents of <%= yield %>. When I make the the window thin enough, the About/Contribute links overlap the logo.

**Comment by miljinx** [comment]
I added margin-top space to the footer to prevent the overlap. It seems to work on my browser, would this fix translate to an actual mobile device?

**Comment by Mikeysax** [comment]
This is how you view mobile in the browser:

![viewingmobileinspect](https://cloud.githubusercontent.com/assets/15805689/21689975/622be5cc-d340-11e6-8531-8df52b3a3b52.gif)

If you remove the height to the footer it will fix the issues with it overlapping.

**Comment by Mikeysax** [comment]
Good job adding the mobile meta tag. You can close this issue when you are done with it. :+1:

**Comment by jimxlin** [comment]
Removing the height property from footer.scss made no difference. I'm still seeing the overlap problem on mobile when the quote is long enough.
![footer_overlap](https://cloud.githubusercontent.com/assets/12786019/21692101/31362ab4-d330-11e6-9ad6-c1ff13db0be1.png)

**Comment by jimxlin** [comment]
Looking through Developer Tools, it seems that `margin-bottom: 60px;` for the body in footer.scss is somehow being overwritten.
![devtool](https://cloud.githubusercontent.com/assets/12786019/21695805/28b4d0ba-d340-11e6-9863-ef4f6aff2fc7.png)

**Comment by Mikeysax** [comment]
You could use a media query and remove position absolute at 300px width:

```
.footer {
    position: absolute;
    bottom: 0;
    width: 100%;
    height: 60px;
    @media (max-width: 300px) {
       position: inherit;
    }
}
```

**Comment by jimxlin** [comment]
Changing the position makes the footer hug the quote instead of staying at the bottom of the screen. Instead, I fixed the issue by adding a body margin property to master.scss. For some reason footer.scss tends to get it's properties overwritten.
